config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'
  resources :users

  get 'signin' => 'sessions#new'
  delete 'signout' => 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # Validations
  validates :name, presence: true, length: { maximum: 16 }
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6, maximum: 32 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      binding.pry
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password. Try again.'
      render 'new'
    end
  end

  def destroy
    sign_out
    flash[:success] = 'You have been successfully logged out.'
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = 'Welcome to DemoApp!'
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name,
                                   :email,
                                   :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "DemoApp"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container pull-left">
    Copyright &copy; 2014 <a href="#">Neil Calabroso</a>, All rights reserved.
  </div>
</footer>

app/views/layouts/_guest_links.html.erb
<ul class="nav navbar-nav">
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'Help', help_path %></li>
  <li><%= link_to 'Contact', contact_path %></li>
  <li><%= link_to 'About', about_path %></li>
</ul>
<ul class="nav navbar-nav navbar-right">
  <li><%= link_to 'Sign in', signin_path %></li>
</ul>

app/views/layouts/_topbar.html.erb
<header>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button"
                class="navbar-toggle"
                data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'DemoApp', root_path, class: 'navbar-brand' %>
      </div>
      
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if signed_in? %>
          <%= render 'layouts/user_links' %>
        <% else %>
          <%= render 'layouts/guest_links' %>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/_user_links.html.erb
<ul class="nav navbar-nav">
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'Users', users_path %></li>
  <li><%= link_to 'Profile', current_user %></li>
  <li><%= link_to 'Settings', '#' %></li>
</ul>
<ul class="nav navbar-nav navbar-right">
  <li><%= link_to 'Sign out', signout_path, method: "delete" %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield :title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/topbar' %>

<div class="container">
  <div class="main">
    <%= render 'shared/notifications' %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</div>

<%= render 'shared/debug' if Rails.env.development? %>

</body>
</html>

app/views/shared/_debug.html.erb
<div id = "debug" class="alert alert-danger">
  <%= debug(params) %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <p>The form contains <%= pluralize(@user.errors.count, 'error') %>.</p>
    </div>
    <ul class="list-group">
      <% @user.errors.full_messages.each do |msg| %>
        <li class="list-group-item list-group-item-warning"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_notifications.html.erb
<div class="notifications">
  <% flash.each do |key, value| %>
   <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>  
</div>

app/views/static_pages/about.html.erb
<% content_for :title, 'About' %>

<h1>Sample App: About Us</h1>
<p> This is the about page of my sample app.</p>

app/views/static_pages/contact.html.erb
<% content_for :title, 'Contact' %>

<h1>Contact Us</h1>

app/views/static_pages/help.html.erb
<% content_for :title, 'Help' %>

<h1>Sample App: Help</h1>
<p> This is the help page of my sample app.</p>

app/views/static_pages/home.html.erb
<% content_for :title, 'Home' %>

<div class="jumbotron">
  <h1>Demo App</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <%= link_to 'Sign up now!',
              signup_path,
              id: 'sign-up-btn',
              class: 'btn btn-primary btn-lg',
              html: { role: 'button' } %>
  
  <%= link_to 'Learn more',
              about_path,
              id: 'learn-more-btn',
              class: 'btn btn-info btn-primary btn-lg',
              html: { role: 'button' } %>
</div>

app/views/users/_form.html.erb
<%= form_for @user, html: { role: 'form' } do |f| %>
  <%= render 'shared/error_messages' %>
  
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %> 
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, 'Confirmation' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit 'Create new account', class: 'btn btn-primary' %>
<% end %>

app/views/users/new.html.erb
<% content_for :title, 'Sign Up' %>

<div class="sign-up">
  <div class="row">
   <div class="col-md-12 col-lg-6">
    <h1 class="text-center">Sign up</h1>
    <%= render 'form' %>
    </div>
    <div class="col-md-12 col-lg-6">
      <div class="detail">
        <h1>Join us!</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
    </div>
   </div> 
  </div>
</div>

app/views/users/show.html.erb
<% content_for :title, @user.name %>

<div class="user">
  <div class="row">
    <div class="col-lg-4">
      <div class="sidebar">
        <div class="pull-left">
          <%= gravatar_for @user %>  
          <div class="clearfix">
        </div>
        </div>
        <div class="info">
          <h1><%= @user.name %></h1>
          <p><%= @user.email %></p>
        </div>  
      </div>
    </div>
    <div class="col-lg-8">
      <h1>Test</h1>
    </div>  
  </div>
</div>
  